CREATE TABLE IF NOT EXISTS users (
    id          BIGINT         GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)   NOT NULL,
    login       VARCHAR(50)    NOT NULL,
    password    VARCHAR(200)   NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT UQ_USERS_LOGIN UNIQUE (login)
);

CREATE TABLE IF NOT EXISTS roles (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users_roles (
    users_id BIGINT NOT NULL,
    roles_id BIGINT NOT NULL,
    CONSTRAINT fk_users_role FOREIGN KEY (users_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk1_users_role FOREIGN KEY (roles_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS transactions (
    id           BIGINT                        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date         TIMESTAMP WITHOUT TIME ZONE   NOT NULL,
    user_id      BIGINT                        NOT NULL,
    type         INTEGER                       NOT NULL,
    category     INTEGER                       NOT NULL,
    count        FLOAT                         NOT NULL,
    CONSTRAINT pk_transaction PRIMARY KEY (id),
    CONSTRAINT fk_transaction FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);